### ISSUE TITLE
rough draft of introduction

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#1]

**Comment by nrnrnr** [comment]
Norman will review

**Comment by rogerburtonpatel** [comment]
Posting this when it's a little more workable from your end. End of weekend.

**Comment by rogerburtonpatel** [comment]
Finished today. Sleeping on it and posting tomorrow.

**Comment by rogerburtonpatel** [comment]
Notes:

I like the first part, up to the last 2 sentences. 
1. I don't know if the last sentence is true, even if the first is hypothetically true.
   I'd like your input on this.
3. The last sentence is ugly and boring. I want to include these details, but don't know if this
   is the right place for them.

Other things:
- I looked up the history of pattern matching and came upon the more precise definition of Tree patterns. 
  I think it's good to include; correct me if I'm wrong. I definitely want to be precise in this. 

- Do I need to define expressiveness in the intro? "Probably not" was my thought. That said, I don't want
  a pro reading my paper to say, "He's using the word 'expressiveness' here without defining it; he has no
  idea what he's talking about.
- This sentence:
  'We go on to claim that there are no programs generatable with the subset that cannot be created 
using pattern matching with popular extensions, implying set equality. '

needs work. I like its ideas but not its form. Would very much appreciate workshopping this, and the last 
sentence, with you. Thank you as always. 



Overall, I'm fairly happy with this as a shitty first draft. It's got a long way to go!

**Comment by nrnrnr** [comment]
For now I think we're good here.  Can reopen when it's time.
