### ISSUE TITLE
Develop a desugaring of Scheme `cond` form into Verse

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#2]
This will make equivalent code more readable and save lots of writing `else wrong`.

**Comment by rogerburtonpatel** [comment]
See comment on issue #3, bullet 3.

**Comment by nrnrnr** [comment]
Is this still worth doing?  I'm inclined to think so.   Either it should be easy or it should expose issues that need to be exposed.

Knock it off before our next meeting?

**Comment by rogerburtonpatel** [comment]
Yes! Though, to be honest, I'm curious what exactly you mean by this. 

My understanding is to have `cond` as a form with a keyword that allows for multiple branches and an implicit `else wrong` at the end. Do we not already have this with `if ... fi`? 

Or, is it that `if ... fi` is sugar for nested `if`s, and we need a proof of the desugaring? 

Or, I'm missing something.

**Comment by rogerburtonpatel** [comment]
That said, a sample desugaring of cond now exists [here](https://github.com/rogerburtonpatel/vml/blob/main/tex/translations/cond-desugar.pdf). Let's discuss and see what's right and wrong with it on this thread.

**Comment by nrnrnr** [comment]
I think I must have been using `cond` as a synonym for `if ... fi`.  (Perils of working with somebody who is not accustomed to saying when concrete syntax is and is not important.)

Your desugaring falls mostly into the category of "easy and knocked off."  Except for one thing: I think it better to desugar directly into core Verse, not into `if` which is itself syntactic sugar.

I recommend you do that, declare victory, and close this issue.

**Comment by rogerburtonpatel** [comment]
⛳️
