### ISSUE TITLE
State formally a soundness theorem for the operational semantics of V-minus

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#20]
No need to prove anything, but what would it mean for the operational semantics to be sound (i.e., correct)?

**Comment by nrnrnr** [comment]
I want you to think about the technicalities, so I'm not going to get too technical in my response, but here's the basic question: On what grounds can we claim that the language V-minus is a subset of (or otherwise related to) Verse?

The answer to that question has to appeal to your operational semantics and to the rewrite rules in the paper, since those two artifacts provide the only precise definitions we have.

**Comment by rogerburtonpatel** [comment]
Got it. Thanks!

**Comment by rogerburtonpatel** [comment]
[.](https://github.com/rogerburtonpatel/vml/blob/main/tex/paper-sections/soundness-theorem.pdf)

**Comment by nrnrnr** [comment]
Write down today's convo and close.

**Comment by rogerburtonpatel** [comment]
Completed this a few days ago. Integrating with main document.
