### ISSUE TITLE
P+ → V-, V- → D, V- → V

### ISSUE THREAD

**Issue by rogerburtonpatel** [rogerburtonpatel/vml#29]
The three translations; two non-trivial. To do this:

1. Formalize P+ and V- (with new judgement form, #21 and #24 )
2. Translate P+ to V- in theory and code (#22 )
3. Formalize Verse (implementation not yet needed, may collect from Verse people) (#18)
4. Translate V- to Verse formally 
5. Finalize formalization of D 
6. Translate V- to D in theory and code (#18)

One wonder: Where does #19 fit into this story?

**Comment by nrnrnr** [comment]
#19 is a prototype for item 6 on your list (translate V- to D)

**Comment by rogerburtonpatel** [comment]
P+ -> V- done, needs theory. 
V- -> V in the works, so is V- -> D.

**Comment by rogerburtonpatel** [comment]
Closing as too broad.
