### ISSUE TITLE
Thesis chapter: pattern matching and its extensions

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#32]
Chapter to answer these questions:

  - What is pattern matching?
  - Why do people like it?
  - What are the (some?) extensions that have been proposed?
  - Why do people want these extensions?
  
A condensed version of this chapter can appear in an eventual paper.

**Comment by rogerburtonpatel** [comment]
This chapter is now well underway, and has provided many interesting examples.

**Comment by rogerburtonpatel** [comment]
Closing as completed.
