### ISSUE TITLE
Pair programming options

### ISSUE THREAD

**Issue by rogerburtonpatel** [rogerburtonpatel/vml#34]
Thank you for offering more pair programming time! I'd also be excited to continue. 

The things I think I would get the most juice out of are-- choose any #-- :

1.  **Biggest one:** The match compiler from VMinus to Decision trees has been a bogeyman for a bit. Tackling it with you would be very helpful for me. 
2. `freshnames.sml` simply does not provide fresh names relative to an existing environment yet. Finding where to produce fresh names, and doing so appropriately, would be awesome. 
3. Getting the parser to recognize input that currently causes the OOM crash mentioned in #33 would make the syntax of PPlus a bit nicer.

**Comment by nrnrnr** [comment]
Any of these work for me.

I've emailed my code for match compilation as source-to-source transformation.  All it does is eliminate nested patterns, but for code generation, that's enough.
