### ISSUE TITLE
refine status of variables in match compilation

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#37]
I recommend that when you are compiling to decision trees, redefine the status type as follows:

``` sml
datatype 'a status = KNOWN | UNKNOWN | LET_BOUND of 'a V.exp
```

When match compilation gets stuck or something else goes wrong, the extra contextual information will be invaluable.

**Comment by rogerburtonpatel** [comment]
Closing as referenced prereq.
