### ISSUE TITLE
what concept replaces "scrutinee" in Verse?

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#5]
The first example in the Verse paper appears problematic because "there's no scrutinee."  But in the Verse terms obtained by translation from $P$, there is not _obviously_ a scrutinee.  So what concept about or property of Verse terms stands in for "there is a scrutinee?"

**Comment by rogerburtonpatel** [comment]
This is a hard problem. Sincerely, very exciting.

**Comment by nrnrnr** [comment]
This one is still valuable, but I don't want to put a hard time suggestion on it.
