### ISSUE TITLE
Complete syntax and forms of judgment for V-

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#6]
Also, attempt some evaluation rules (possibly not complete).

**Comment by rogerburtonpatel** [comment]
Tomorrow

**Comment by rogerburtonpatel** [comment]
Some steps for this exist in https://github.com/rogerburtonpatel/vml/issues/10.

**Comment by nrnrnr** [comment]
Done at the board today for V-minus without choice.
