### ISSUE TITLE
A *formal* attempt at "like pattern matching"

### ISSUE THREAD

**Issue by nrnrnr** [rogerburtonpatel/vml#7]
Pick something that might mean "like pattern matching" and try to formalize it.  Issue #4 is an option but not the only option.

**Comment by rogerburtonpatel** [comment]
I think "like pattern matching" means you can compile it to a decision tree. 

Writing this here so I don't forget, and so you see it.

**Comment by nrnrnr** [comment]
I suspect this property will be difficult to formalize in a useful way.  But I will look forward to seeing what you have by Thursday.

**Comment by rogerburtonpatel** [comment]
https://github.com/rogerburtonpatel/vml/commit/e8967e5cfaa717ebfeba926f677adbe76c1c50a7

**Comment by nrnrnr** [comment]
FYI, github is rendering the $\;$ as a semicolon: https://github.com/rogerburtonpatel/vml/blob/main/like-pattern-matching.md


Other comments:

  - I'm not seeing the cycle among $x, y, z$.  I'm seeing "x depends on y; x depends on z".  But those equations aren't `let` bindings.  What are you seeing for dependencies?

  - According to Figure 1 in the Verse paper, a logical variable can be a value.  So your `value_bound_var` doesn't create the restriction you are hoping for.
  
  - The draft is still from formal.  And I don't yet grasp the idea well enough to be confident that it is ready to formalize.  In particular, I worry that "dependency graph" is a complex concept.  Perhaps there is a simpler piece of spaghetti to pull on?

**Comment by rogerburtonpatel** [comment]
> FYI, github is rendering the ; as a semicolon: https://github.com/rogerburtonpatel/vml/blob/main/like-pattern-matching.md

Gosh darn it. Missed this. Just want my latex \; spaces. Thanks for the heads-up. 

> Other comments:
> 
>     * I'm not seeing the cycle among x,y,z.  I'm seeing "x depends on y; x depends on z".  But those equations aren't `let` bindings.  What are you seeing for dependencies?

I see a logical variable $x$ that depend on tuples containing logical variables $y, z$. Those variables, in turn, don't depend on external values. They're only related to $x$. I agree that I need to formalize this idea. Does what I'm getting at- that logical variables that depend only on logical variables with no overall scrutinee is what creates logical-variables-at-runtime scenarios? 

>     * According to Figure 1 in the Verse paper, a logical variable can be a value.  So your `value_bound_var` doesn't create the restriction you are hoping for.

Yep. I'll fix this. 

>     * The draft is still from formal.  And I don't yet grasp the idea well enough to be confident that it is ready to formalize.  In particular, I worry that "dependency graph" is a complex concept.  Perhaps there is a simpler piece of spaghetti to pull on?

I agree. I'll think on this more. Thank you for your sincerity.

**Comment by rogerburtonpatel** [comment]
Revising tomorrow with translations.
